// src/components/TimeBadge.vue
<template>
  <b-badge v-bind:variant="mutableVariant" v-bind:class="{ 'pull-right': pullright }" class="align-middle">
    {{ disp }}
  </b-badge>
</template>

<script>
import dayjs from 'dayjs';
import duration from 'dayjs/plugin/duration';
dayjs.extend(duration);

export default {
  name: 'TimeBadge',
  props: {
    starttime: {
      type: String,
      default: '1970-01-01T00:00:00.000Z',
    },
    endtime: {
      type: String,
      default: '1970-01-01T00:00:00.000Z',
    },
    text: {
      type: String,
      default: '0s',
    },
    variant: {
      type: String,
      default: 'info',
    },
    interval: {
      type: Number,
      default: 60000,
    },
    counter: {
      type: Boolean,
      default: false,
    },
    pullright: {
      type: Boolean,
      default: true,
    },
  },
  mounted: function () {
    this.onBadgeUpdate();
  },
  data: function () {
    return {
      disp: this.text,
      mutableVariant: this.variant,
    };
  },
  methods: {
    formatDurationShort(duration) {
      let timeText = '';
      if (duration.days()) {
        timeText += `${duration.days()}d ${duration.hours()}h ${duration.minutes()}m ${duration.seconds()}s`;
      } else if (duration.hours()) {
        timeText += `${duration.hours()}h ${duration.minutes()}m ${duration.seconds()}s`;
      } else if (duration.minutes()) {
        timeText += `${duration.minutes()}m ${duration.seconds()}s`;
      } else {
        timeText += `${duration.seconds()}s`;
      }
      if (timeText.includes('-')) {
        this.$parent.$forceUpdate();
      }
      return timeText;
    },
    formatTimer(diff) {
      let timeLeft = diff;
      const stringArray = [];

      [
        [86400000, 'd'],
        [3600000, 'h'],
        [60000, 'm'],
        [1000, 's'],
      ].forEach(([unit, suffix]) => {
        const time = Math.floor(timeLeft / unit);
        const first = stringArray.length === 0;
        if (!first || time > 0) {
          stringArray.push(time.toString().padStart(first ? 1 : 2, '0') + suffix);
        }
        timeLeft -= time * unit;
      });
      return stringArray.join(' ');
    },
    onBadgeUpdate() {
      let diffactivate;
      let durationactivate;

      const start = new Date(this.starttime).getTime() / 1000;

      if (typeof start !== 'undefined' && start !== false) {
        diffactivate = dayjs().diff(dayjs(start).unix()) * -1;
        durationactivate = dayjs.duration(diffactivate, 'milliseconds');
      }

      if (!this.counter) {
        const end = new Date(this.endtime).getTime() / 1000;

        // Get the diff and duration until "end"
        const diff = dayjs().diff(dayjs.unix(end)) * -1;
        const duration = dayjs.duration({ milliseconds: diff });

        duration.parseFromMilliseconds();
        durationactivate.parseFromMilliseconds();

        // Format based on there being no end time, being after the end, or being before the start
        if (!this.endtime) {
          this.disp = `${diffactivate > 0 ? '-' : ''}${this.formatTimer(Math.abs(diffactivate))}`;
        } else if (typeof diffactivate !== 'undefined' && diffactivate > 0) {
          this.mutableVariant = 'info';
          this.disp = `${this.$t('time.startL')} ${this.formatDurationShort(durationactivate)}`;
        } else if (diff < 0) {
          this.mutableVariant = 'info';
          this.disp = `${this.$t('time.expiredL')}: ${this.formatDurationShort(duration)}`;
        } else {
          if (diff < 600000) {
            // 0 min to 10 min
            this.mutableVariant = 'danger';
          } else if (diff < 1800000) {
            // 10 min to 30 min
            this.mutableVariant = 'warning';
          } else if (diff > 1800000) {
            // 30 min to 1 hour
            this.mutableVariant = 'success';
          } else {
            this.mutableVariant = 'info';
          }
          this.disp = this.formatTimer(diff);
        }
      } else {
        const diff = dayjs().diff(dayjs.unix(start));
        const duration = dayjs.duration({ milliseconds: diff });

        durationactivate.parseFromMilliseconds();
        duration.parseFromMilliseconds();

        this.mutableVariant = 'transparent';
        if (typeof diffactivate !== 'undefined' && diffactivate > 0) {
          this.disp = `${this.$t('time.startL')} ${this.formatDurationShort(durationactivate)}`;
        } else {
          this.disp = `${this.$t('time.ongoingL')} ${this.formatDurationShort(duration)}`;
        }
      }

      setTimeout(this.onBadgeUpdate, this.interval);
    },
  },
};
</script>

// components/ui/TimeBadge/TimeBadge.component.tsx
'use client';
import './TimeBadge.component.scss';

import { useCallback, useEffect, useState, type CSSProperties, type FC } from 'react';
import { Chip } from '@heroui/react';
import dayjs from 'dayjs';
import durationPlugin from 'dayjs/plugin/duration';
import { useTranslation } from 'react-i18next';

import { isRealInstant, parseInstant } from '@/lib/shared/time';

dayjs.extend(durationPlugin);

type DayjsDuration = ReturnType<typeof dayjs.duration>;

const tenMinutes = 600000;
const thirtyMinutes = 1800000;
const sixtyMinutes = 3600000;
const defaultCoarseHoursAbove = 7200000;

export type TimeBadgeTone = 'info' | 'success' | 'warning' | 'danger' | 'transparent';

type ChipColor = 'accent' | 'success' | 'warning' | 'danger' | 'default';

export { parseInstant } from '@/lib/shared/time';

export const timeBadgeChipColor = (tone: TimeBadgeTone | string): ChipColor => {
  if (tone === 'info' || tone === 'accent') return 'accent';
  if (tone === 'success' || tone === 'warning' || tone === 'danger') return tone;
  return 'default';
};

type TimeBadgeProps = {
  starttime?: string;
  endtime?: string;
  text?: string;
  variant?: TimeBadgeTone;
  interval?: number;
  counter?: boolean;
  pullright?: boolean;
  className?: string;
  style?: CSSProperties;
  id?: string;
  /** When remaining ms is at or above this threshold, show hours only (e.g. 2h, 1d 3h). Pass `null` to disable. */
  coarseHoursAbove?: number | null;
};

export const formatTimer = (diff: number): string => {
  if (!Number.isFinite(diff) || diff < 0) {
    return '0s';
  }

  let timeLeft = diff;
  const stringArray: string[] = [];

  (
    [
      [86400000, 'd'],
      [3600000, 'h'],
      [60000, 'm'],
      [1000, 's'],
    ] as const
  ).forEach(([unit, suffix]) => {
    const time = Math.floor(timeLeft / unit);
    const first = stringArray.length === 0;
    if (!first || time > 0) {
      stringArray.push(time.toString().padStart(first ? 1 : 2, '0') + suffix);
    }
    timeLeft -= time * unit;
  });
  return stringArray.join(' ') || '0s';
};

export const formatTimerCoarseHours = (diff: number): string => {
  if (!Number.isFinite(diff) || diff < 0) {
    return '0h';
  }

  const totalHours = Math.ceil(diff / 3600000);
  if (totalHours <= 0) {
    return '0h';
  }

  const days = Math.floor(totalHours / 24);
  const hours = totalHours % 24;

  if (days > 0) {
    return hours > 0 ? `${days}d ${hours}h` : `${days}d`;
  }

  return `${totalHours}h`;
};

const formatDurationShort = (d: DayjsDuration, coarseHoursAbove?: number): string => {
  const ms = Math.abs(d.asMilliseconds());
  if (coarseHoursAbove !== undefined && ms >= coarseHoursAbove) {
    return formatTimerCoarseHours(ms);
  }

  let timeText = '';
  if (d.days()) {
    timeText += `${d.days()}d ${d.hours()}h ${d.minutes()}m ${d.seconds()}s`;
  } else if (d.hours()) {
    timeText += `${d.hours()}h ${d.minutes()}m ${d.seconds()}s`;
  } else if (d.minutes()) {
    timeText += `${d.minutes()}m ${d.seconds()}s`;
  } else {
    timeText += `${d.seconds()}s`;
  }
  if (timeText.includes('-')) {
    timeText = `-${timeText.replace(/-/g, '')}`;
  }
  return timeText;
};

const formatCountdown = (diff: number, coarseHoursAbove?: number): string => {
  if (coarseHoursAbove !== undefined && diff >= coarseHoursAbove) {
    return formatTimerCoarseHours(diff);
  }
  return formatTimer(diff);
};

const TimeBadge: FC<TimeBadgeProps> = ({
  starttime = '1970-01-01T00:00:00.000Z',
  endtime = '1970-01-01T00:00:00.000Z',
  text = '0s',
  variant = 'info',
  interval = 60000,
  counter = false,
  pullright = true,
  className,
  style,
  id,
  coarseHoursAbove = defaultCoarseHoursAbove,
}: TimeBadgeProps) => {
  const { t } = useTranslation();
  const [disp, setDisp] = useState(text);
  const [tone, setTone] = useState<TimeBadgeTone>(variant);
  const [tickInterval, setTickInterval] = useState(interval);

  const onBadgeUpdate = useCallback(() => {
    const coarseAbove = coarseHoursAbove ?? undefined;
    const startAt = parseInstant(starttime);
    const endAt = parseInstant(endtime);
    const start = isRealInstant(startAt) ? startAt : undefined;
    const end = isRealInstant(endAt) ? endAt : undefined;

    let diffactivate: number | undefined;
    let durationactivate: DayjsDuration | undefined;

    if (start) {
      diffactivate = start.diff(dayjs(), 'millisecond');
      durationactivate = dayjs.duration(diffactivate);
    }

    if (!counter) {
      if (!end) {
        setTone('info');
        setTickInterval(interval);
        setDisp(
          `${diffactivate && diffactivate > 0 ? '-' : ''}${formatCountdown(Math.abs(diffactivate ?? 0), coarseAbove)}`
        );
        return;
      }

      const diff = end.diff(dayjs(), 'millisecond');
      const duration = dayjs.duration(Math.abs(diff));
      const useCoarse = coarseAbove !== undefined && diff >= coarseAbove;

      if (diffactivate && diffactivate > 0) {
        setTone('info');
        setTickInterval(useCoarse ? 60000 : interval);
        setDisp(`${t('time.startL')} ${formatDurationShort(durationactivate!, coarseAbove)}`);
      } else if (diff <= 0) {
        setTone('info');
        setTickInterval(interval);
        setDisp(`${t('time.expiredL')}: ${formatDurationShort(duration, coarseAbove)}`);
      } else {
        if (diff < tenMinutes) {
          setTone('danger');
        } else if (diff < thirtyMinutes) {
          setTone('warning');
        } else if (diff < sixtyMinutes) {
          setTone('success');
        } else {
          setTone('info');
        }
        setTickInterval(useCoarse ? 60000 : Math.min(interval, 1000));
        setDisp(formatCountdown(diff, coarseAbove));
      }
    } else {
      const diff = start ? dayjs().diff(start, 'millisecond') : 0;
      const duration = dayjs.duration(diff);
      const useCoarse = coarseAbove !== undefined && diff >= coarseAbove;

      setTone('transparent');
      setTickInterval(useCoarse ? 60000 : interval);
      if (diffactivate && diffactivate > 0) {
        setDisp(`${t('time.startL')} ${formatDurationShort(durationactivate!, coarseAbove)}`);
      } else {
        setDisp(`${t('time.ongoingL')} ${formatDurationShort(duration, coarseAbove)}`);
      }
    }
  }, [starttime, endtime, counter, t, interval, coarseHoursAbove]);

  useEffect(() => {
    onBadgeUpdate();
    const timerId = setInterval(onBadgeUpdate, tickInterval);
    return () => clearInterval(timerId);
  }, [onBadgeUpdate, tickInterval]);

  const classes = [
    'hub-time-badge inline-flex items-center gap-1',
    pullright ? 'float-right' : '',
    'align-middle',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <Chip id={id} className={classes} color={timeBadgeChipColor(tone)} size='sm' variant='soft' style={style}>
      {disp}
    </Chip>
  );
};

export { defaultCoarseHoursAbove };

/** Smaller chip layout for dense rows (sales, darvo, cycle bar). */
export const compactTimeBadgeProps = {
  className: 'text-[0.62rem] min-h-[1.05rem] px-1.5',
  pullright: false,
} as const;

export default TimeBadge;
