// src/components/CodexCard.vue
<template>
  <b-card no-body :header="this.item.name">
    <b-card-img :src="this.wfcdn(this.item.imageName)" :alt="this.item.name" top />
    <b-card-body>
      <b-card-text>
        <slot name="t1">
          {{ description || item.description || '' }}
        </slot>
      </b-card-text>
      <b-card-text>
        <slot name="t2"></slot>
      </b-card-text>
      <b-button v-if="this.link" :href="this.link" target="_blank" variant="primary">
        Wiki <i class="fas fa-link" />
      </b-button>
      <b-button v-else @click="modal.open()"> Wiki <i class="fas fa-link" /> </b-button>
      <b-button v-if="!!link2" :href="link2.a" target="_blank" variant="primary">
        {{ link2.title }} <i class="fas fa-link" />
      </b-button>
    </b-card-body>
  </b-card>
</template>

<script>
import { cdn, wfcdn, optimize } from '@/utilities';

export default {
  name: 'CodexCard',
  props: {
    item: Object,
    description: String,
    link: String,
    link2: Object,
  },
  methods: {
    cdn,
    wfcdn,
    optimize,
  },
};
</script>

<style scoped></style>

// components/ui/CodexCard/CodexCard.component.tsx
'use client';

import { useEffect, useState, type FC, type ReactNode } from 'react';
import { Button, Card } from '@heroui/react';
import { fetchItemByUniqueName, wfcdn } from '@/lib/shared';

type CodexItem = {
  name: string;
  uniqueName?: string;
  imageName?: string;
  description?: string;
};

type CodexCardProps = {
  item: CodexItem;
  description?: string;
  link?: string;
  link2?: { a: string; title: string };
  children?: ReactNode;
};

const CodexCard: FC<CodexCardProps> = ({ item, description, link, link2, children }: CodexCardProps) => {
  const [imageName, setImageName] = useState(item.imageName ?? '');

  useEffect(() => {
    if (item.imageName) {
      setImageName(item.imageName);
      return;
    }

    if (!item.uniqueName) return;

    let cancelled = false;
    void fetchItemByUniqueName(item.uniqueName).then((data) => {
      if (!cancelled && data?.imageName) setImageName(data.imageName);
    });

    return () => {
      cancelled = true;
    };
  }, [item.imageName, item.uniqueName]);

  return (
    <Card className="hub-codex-card">
      <Card.Header className="hub-codex-card__header">{item.name}</Card.Header>
      <Card.Content className="hub-codex-card__content">
        {imageName ? (
          <img className="hub-codex-card__image" src={wfcdn(imageName)} alt={item.name} />
        ) : null}
        <p className="hub-codex-card__text">{children ?? description ?? item.description ?? ''}</p>
        <div className="hub-codex-card__actions">
          {link ? (
            <Button
              size="sm"
              variant="primary"
              className="hub-content-btn"
              onPress={() => window.open(link, '_blank', 'noopener,noreferrer')}
            >
              Wiki <i className="fas fa-link" />
            </Button>
          ) : null}
          {link2 ? (
            <Button
              size="sm"
              variant="primary"
              className="hub-content-btn"
              onPress={() => window.open(link2.a, '_blank', 'noopener,noreferrer')}
            >
              {link2.title} <i className="fas fa-link" />
            </Button>
          ) : null}
        </div>
      </Card.Content>
    </Card>
  );
};

export default CodexCard;
