// components/panels/worldstate/ConstructionPanel/ConstructionPanel.component.tsx
'use client';
import './ConstructionPanel.component.scss';
import type { FC } from 'react';

import { useTranslation } from 'react-i18next';
import NoDataItem from '@/components/ui/NoDataItem';
import HubPanelWrap from '@/components/panels/shared/HubPanelWrap';
import { HubPanelList, HubPanelListItem } from '@/components/panels/shared/HubPanelList';

const normalize = (num: number): number => {
  if (num > 100) return normalize(num - 100);
  if (num < 0) return 0;
  return num;
};

const percent = (str: string | number | undefined): number => {
  const num = normalize(Number.parseFloat(String(str ?? '0.00')));
  return Number.parseFloat(num.toFixed(2));
};

type EllipseProgressProps = {
  progress: number;
  color: string;
  size?: number;
  caption: string;
};

const EllipseProgress: FC<EllipseProgressProps> = ({ progress, color, size = 100, caption }: EllipseProgressProps) => {
  const stroke = 8;
  const radius = (size - stroke) / 2;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference - (progress / 100) * circumference;

  return (
    <div className='construction-wrapper text-center'>
      <div className='construction-ring' style={{ width: size, height: size }}>
        <svg width={size} height={size} style={{ transform: 'rotate(-90deg)' }}>
          <circle cx={size / 2} cy={size / 2} r={radius} fill='none' stroke='#222' strokeWidth={stroke} />
          <circle
            cx={size / 2}
            cy={size / 2}
            r={radius}
            fill='none'
            stroke={color}
            strokeWidth={stroke}
            strokeDasharray={circumference}
            strokeDashoffset={offset}
            strokeLinecap='round'
          />
        </svg>
        <div className='construction-ring-value'>{progress}%</div>
      </div>
      <p className='legend-caption'>{caption}</p>
    </div>
  );
};

type Construction = {
  fomorianProgress?: string | number;
  razorbackProgress?: string | number;
};

type ConstructionPanelProps = {
  construction?: Construction;
};

const ConstructionPanel: FC<ConstructionPanelProps> = ({
  construction = { fomorianProgress: 0, razorbackProgress: 0 },
}: ConstructionPanelProps) => {
  const { t } = useTranslation();
  const headertext = t('construction.header');
  const hasData = construction && Object.keys(construction).length > 2;

  return (
    <HubPanelWrap title={headertext} className='construction'>
      {hasData ? (
        <HubPanelList>
          <HubPanelListItem borderless className='hub-construction-row'>
            <EllipseProgress
              progress={percent(construction.fomorianProgress)}
              color='#ff0000'
              caption={t('construction.fomorian')}
            />
            <EllipseProgress
              progress={percent(construction.razorbackProgress)}
              color='#5BACF7'
              caption={t('construction.razorback')}
            />
          </HubPanelListItem>
        </HubPanelList>
      ) : (
        <NoDataItem text={headertext} />
      )}
    </HubPanelWrap>
  );
};

export default ConstructionPanel;

// src/components/panels/ConstructionPanel.vue
<template>
  <HubPanelWrap :title="headertext" class="construction">
    <b-list-group>
      <b-list-group-item
        v-if="construction && Object.keys(construction).length > 2"
        class="list-group-item-borderbottom"
      >
        <div class="construction-wrapper text-center">
          <VueCircle
            ref="fomoProgress"
            :progress="0"
            :size="75"
            :fill="{ color: '#ff0000' }"
            class="prog-circle"
            title="Fomorian Progress"
            :start-angle="-Math.PI / 2"
          ></VueCircle>
          <div class="text-center">{{ $t('construction.fomorian') }}</div>
        </div>
        <div class="construction-wrapper text-center">
          <VueCircle
            ref="razorProgress"
            :progress="0"
            :size="75"
            :fill="{ color: '#5BACF7' }"
            class="prog-circle"
            title="Razorback Progress"
            :start-angle="-Math.PI / 2"
          ></VueCircle>
          <div class="text-center">{{ $t('construction.razorback') }}</div>
        </div>
        <div class="construction-wrapper text-center">
          <VueCircle
            ref="unkProgress"
            :progress="0"
            :size="75"
            :fill="{ color: '#738BDA' }"
            class="prog-circle"
            title="Unknown Progress"
            :start-angle="-Math.PI / 2"
          ></VueCircle>
          <div class="text-center">{{ $t('construction.unk') }}</div>
        </div>
      </b-list-group-item>
    </b-list-group>
    <b-list-group v-if="!construction || Object.keys(construction).length < 2" class="list-group-item-borderbottom">
      <NoDataItem :text="headertext" />
    </b-list-group>
  </HubPanelWrap>
</template>

<style>
.construction-wrapper {
  width: 33%;
  float: left;
}
</style>

<script>
import VueCircle from 'vue2-circle-progress';

import NoDataItem from '@/components/NoDataItem.vue';
import HubPanelWrap from '@/components/HubPanelWrap';

export default {
  name: 'Construction',
  props: ['construction'],
  computed: {
    headertext() {
      return this.$t('construction.header');
    },
  },
  methods: {
    percent: (str) => Number.parseFloat(str || '0.00'),
  },
  mounted() {
    this.$refs.fomoProgress.updateProgress(this.percent(this.construction.fomorianProgress));
    this.$refs.razorProgress.updateProgress(this.percent(this.construction.razorbackProgress));
    this.$refs.unkProgress.updateProgress(this.percent(this.construction.unknownProgress));
  },
  updated() {
    this.$refs.fomoProgress.updateProgress(this.percent(this.construction.fomorianProgress));
    this.$refs.razorProgress.updateProgress(this.percent(this.construction.razorbackProgress));
    this.$refs.unkProgress.updateProgress(this.percent(this.construction.unknownProgress));
  },
  data() {
    return {
      styleObject: {
        display: 'inline',
      },
    };
  },
  components: {
    NoDataItem,
    HubPanelWrap,
    VueCircle,
  },
};
</script>
