// components/panels/worldstate/VoidTraderPanel/VoidTraderPanel.component.tsx
'use client';
import './VoidTraderPanel.component.scss';
import type { FC } from 'react';

import { Table } from '@heroui/react';
import { useTranslation } from 'react-i18next';
import TimeBadge from '@/components/ui/TimeBadge';
import HubPanelWrap from '@/components/panels/shared/HubPanelWrap';
import { HubPanelList, HubPanelListItem } from '@/components/panels/shared/HubPanelList';

type VoidTraderItem = {
  item: string;
  ducats: number;
  credits: number;
};

type VoidTrader = {
  activation: string;
  expiry: string;
  location: string;
  inventory?: VoidTraderItem[];
};

type VoidTraderPanelProps = {
  voidTrader?: VoidTrader;
};

const VoidTraderPanel: FC<VoidTraderPanelProps> = ({ voidTrader = {} as VoidTrader }: VoidTraderPanelProps) => {
  const { t } = useTranslation();
  const headertext = t('vt.header');
  const items = voidTrader.inventory || [];
  const available = (voidTrader.inventory?.length ?? 0) > 0;

  const locationLabel = () => `${t(`time.${available ? 'depart' : 'arrive'}`)} ${voidTrader.location}:`;

  return (
    <HubPanelWrap title={headertext} className="baro">
      <HubPanelList>
        <HubPanelListItem borderless={available} borderBottom={!available}>
          <span className="float-left">{locationLabel()}</span>
          <TimeBadge starttime={voidTrader.activation} endtime={voidTrader.expiry} interval={1000} />
        </HubPanelListItem>
        {available && (
          <HubPanelListItem borderBottom>
            <Table className="hub-baro-table" variant="primary" aria-label={headertext}>
              <Table.ScrollContainer>
                <Table.Content>
                  <Table.Header>
                    <Table.Column isRowHeader>{t('vt.item')}</Table.Column>
                    <Table.Column className="hub-baro-col-ducats">{t('currency.dabloons')}</Table.Column>
                    <Table.Column className="hub-baro-col-credits">{t('currency.cred')}</Table.Column>
                  </Table.Header>
                  <Table.Body>
                    {items.map((item, i) => (
                      <Table.Row key={i}>
                        <Table.Cell>{item.item}</Table.Cell>
                        <Table.Cell className="hub-baro-col-ducats">{item.ducats}</Table.Cell>
                        <Table.Cell className="hub-baro-col-credits">{item.credits}</Table.Cell>
                      </Table.Row>
                    ))}
                  </Table.Body>
                </Table.Content>
              </Table.ScrollContainer>
            </Table>
          </HubPanelListItem>
        )}
      </HubPanelList>
    </HubPanelWrap>
  );
};

export default VoidTraderPanel;

// src/components/panels/VoidTraderPanel.vue
<template>
  <HubPanelWrap :title="headertext" class="baro">
    <b-list-group>
      <b-list-group-item :class="`${available() ? 'list-group-item-borderless' : 'list-group-item-borderbottom'}`">
        <span class="pull-left">{{ locationLabel() }}</span>
        <TimeBadge :starttime="voidTrader.activation" :endtime="voidTrader.expiry" :interval="1000" />
      </b-list-group-item>
      <b-list-group-item
        class="list-group-item-borderbottom"
        v-if="available()"
        :items="this.items"
        :fields="this.fields"
      >
        <b-table class="thin item-table" :items="this.items" :fields="this.fields" />
      </b-list-group-item>
    </b-list-group>
  </HubPanelWrap>
</template>

<script>
import dayjs from 'dayjs';

import TimeBadge from '@/components/TimeBadge.vue';
import HubPanelWrap from '@/components/HubPanelWrap';

export default {
  name: 'VoidTraderPanel',
  props: ['voidTrader'],
  computed: {
    headertext() {
      return this.$t('vt.header');
    },
  },
  data() {
    return {
      items: this.voidTrader.inventory || [],
      fields: [
        {
          key: 'item',
          label: this.$t('vt.item'),
          thClass: 'text-center col-xs-6',
        },
        {
          key: 'ducats',
          label: this.$t('currency.dabloons'),
          thClass: 'text-center col-xs-2',
        },
        {
          key: 'credits',
          label: this.$t('currency.cred'),
          thClass: 'text-center col-xs-4',
        },
      ],
    };
  },
  components: {
    HubPanelWrap,
    TimeBadge,
  },
  methods: {
    now() {
      return new Date().toString();
    },
    available() {
      return this.voidTrader.inventory.length > 0;
    },
    hereTime() {
      return dayjs(this.available() ? this.voidTrader.expiry : this.voidTrader.activation).format('llll');
    },
    locationLabel() {
      return `${this.$t(`time.${this.available() ? 'depart' : 'arrive'}`)} ${this.voidTrader.location}:`;
    },
  },
};
</script>
