// src/components/panels/NewsPanel.vue
<template>
  <HubPanelWrap :title="headertext">
    <b-list-group>
      <b-list-group-item class="list-group-item-borderless">
        <b-carousel
          id="infoscreen-carousel"
          :interval="0"
          :value="cycle ? activeElemIndex % filteredNews.length : hover"
          :indicators="false"
          :controls="false"
        >
          <b-carousel-slide v-for="newsitem in filteredNews" :key="`${newsitem.id}-img`">
            <b-img
              slot="img"
              :alt="newsitem.message"
              class="d-block slide-image"
              fluid
              center
              :src="getImgSrc(newsitem.imageLink)"
            />
          </b-carousel-slide>
        </b-carousel>
      </b-list-group-item>
      <b-list-group-item class="list-group-item-borderless pb-0">
        <b-list-group>
          <b-list-group-item
            :data-news-item="newsitem.id"
            :key="`${newsitem.id}-li`"
            :class="`d-flex py-0 justify-content-between align-items-center list-group-item-borderless ${
              cycle && index === activeElemIndex % filteredNews.length ? 'active' : ''
            } ${hover === index ? 'hover' : ''}`"
            v-for="(newsitem, index) in filteredNews"
            @mouseover="hover = index"
          >
            <span class="news-title">
              <b-link target="_blank" rel="noopener" :href="newsitem.link">
                <div class="news-time">{{ title(newsitem).time }}</div>
                <span class="news-label">{{ title(newsitem).label }}</span>
              </b-link>
            </span>
          </b-list-group-item>
        </b-list-group>
      </b-list-group-item>
      <b-list-group-item class="list-group-item-borderbottom">
        <b-form-checkbox id="news-cycle-checkbox" class="float-right" name="news-cycle-checkbox" switch v-model="check">
          {{ this.$t('news.autoprogress') }}
        </b-form-checkbox>
      </b-list-group-item>
    </b-list-group>
  </HubPanelWrap>
</template>
<style scoped>
.list-group .list-group {
  margin: 0 -5px -5px -5px;
}

body .list-group .list-group-item-borderbottom {
  margin: 0;
}

body .list-group .list-group-item-borderless .list-group {
  margin-left: auto;
  margin-right: auto;
  display: inline-block;
}

.list-group-item.active .news-title a,
.list-group-item.hover .news-title a {
  font-weight: normal;
  color: white;
}

.list-group-item.active + .hover .news-title a {
  color: grey;
}

.list-group-item.active .news-title a:hover {
  font-weight: normal;
  color: grey;
}

.list-group .list-group .list-group-item {
  padding-top: 0px;
  padding-right: 0px;
  padding-left: 0px;
}

.news-title {
  text-align: left;
}

.news-time {
  width: 5em;
  float: left;
}
</style>
<script>
import HubPanelWrap from '@/components/HubPanelWrap';

import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';
import updateLocale from 'dayjs/plugin/updateLocale';
dayjs.extend(relativeTime);
dayjs.extend(updateLocale);

const cdnUrl = 'https://cdn.warframestat.us';
const cdnOpts = ['o_webp', 'rs_404x110'];

export default {
  props: ['news'],
  name: 'NewsPanel',
  components: { HubPanelWrap },
  computed: {
    headertext() {
      return this.$t('news.header');
    },
    filteredNews() {
      return this.news.filter((item) => item.translations[this.locale]).reverse();
    },
    check: {
      get() {
        return this.cycle;
      },
      set() {
        this.hover = null;
        this.cycle = !this.cycle;
        this.$store.commit('autoProgressNews', [this.cycle]);
      },
    },
  },
  methods: {
    increment() {
      if (this.cycle) {
        this.activeElemIndex++;
      }
    },
    open: function (url) {
      window.open(url, '_blank');
      this.increment();
    },
    getImgSrc: (url) => {
      return `${cdnUrl}/${cdnOpts.join(',')}/${url}`;
    },
    title: function (newsitem) {
      if (newsitem.startDate && newsitem.endDate) {
        if (dayjs(newsitem.startDate).unix() > dayjs().unix()) {
          return {
            time: dayjs(newsitem.startDate).fromNow(),
            label: newsitem.translations[this.locale],
          };
        } else if (dayjs(newsitem.endDate).unix() > dayjs().unix()) {
          return {
            time: `${this.$t('news.live')}:`,
            label: newsitem.translations[this.locale],
          };
        } else {
          return {
            time: dayjs(newsitem.endDate).fromNow(),
            label: newsitem.translations[this.locale],
          };
        }
      } else {
        return {
          time: dayjs(newsitem.date).fromNow(),
          label: newsitem.translations[this.locale],
        };
      }
    },
  },
  data() {
    return {
      styleObject: {
        display: 'inline',
      },
      activeElemIndex: 0,
      interval: {},
      cycle: this.$store.getters.componentState.news.autoCycle,
      hover: null,
      locale: this.$store.getters.locale,
    };
  },
  mounted() {
    this.interval = setInterval(this.increment, 3000);
    dayjs.updateLocale('en', {
      relativeTime: {
        future: `${this.$t('news.future')} %s:`,
        past: `%s ${this.$t('news.past')}:`,
        s: '%ds',
        m: '1m',
        mm: '%dm',
        h: '1h',
        hh: '%dh',
        d: '1d',
        dd: '%dd',
        M: '1m',
        MM: '%dm',
        y: '1y',
        yy: '%dy',
      },
    });
  },
  beforeDestroy() {
    clearInterval(this.interval);
  },
  beforeUpdate() {
    clearInterval(this.interval);
    this.interval = undefined;
  },
  updated() {
    if (!this.interval) {
      this.interval = setInterval(this.increment, 3000);
    }
  },
};
</script>

// apps/next/components/panels/worldstate/NewsPanel/NewsPanel.component.tsx
'use client';

import { useEffect, useMemo, useState, type FC, type SyntheticEvent } from 'react';
import HubSwitch from '@/components/ui/HubSwitch';
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';
import updateLocale from 'dayjs/plugin/updateLocale';
import { useTranslation } from 'react-i18next';
import { optimize, cdn } from '@wfcd/shared';
import { usePrefs } from '@/lib/providers/PrefsProvider';
import HubPanelWrap from '@/components/panels/shared/HubPanelWrap';
import './NewsPanel.component.scss';

dayjs.extend(relativeTime);
dayjs.extend(updateLocale);

const newsImg = (url: string) => optimize(url, '404x110', 'scale');

const NEWS_PLACEHOLDER_PATH = 'img/news-placeholder.png';
const NEWS_PLACEHOLDER_URL = cdn(NEWS_PLACEHOLDER_PATH);
const NEWS_PLACEHOLDER_SRC = newsImg(NEWS_PLACEHOLDER_URL);

const DEFAULT_NEWS_IMAGE_URLS = new Set([
  'https://i.imgur.com/CNrsc7V.png',
  NEWS_PLACEHOLDER_URL,
  `https://cdn.warframestat.us/genesis/${NEWS_PLACEHOLDER_PATH}`,
  `https://wfcd.github.io/genesis-assets/${NEWS_PLACEHOLDER_PATH}`,
]);

const resolveNewsImageUrl = (url?: string | null): string => {
  const trimmed = url?.trim();
  if (!trimmed || DEFAULT_NEWS_IMAGE_URLS.has(trimmed)) {
    return NEWS_PLACEHOLDER_URL;
  }
  return trimmed;
};

const getNewsImageSrc = (url?: string | null): string => newsImg(resolveNewsImageUrl(url));

type NewsItem = {
  id: string;
  message?: string;
  imageLink?: string;
  link: string;
  date?: string;
  startDate?: string;
  endDate?: string;
  translations: Record<string, string>;
};

type NewsPanelProps = {
  news: NewsItem[];
};

const NewsPanel: FC<NewsPanelProps> = ({ news }: NewsPanelProps) => {
  const { t } = useTranslation();
  const { state, dispatch } = usePrefs();
  const headertext = t('news.header');
  const locale = state.locale;
  const cycle = state.components.news?.autoCycle ?? false;

  const [activeElemIndex, setActiveElemIndex] = useState(0);
  const [hover, setHover] = useState<number | null>(null);

  const filteredNews = useMemo(() => news.filter((item) => item.translations[locale]).reverse(), [news, locale]);

  useEffect(() => {
    dayjs.updateLocale('en', {
      relativeTime: {
        future: `${t('news.future')} %s:`,
        past: `%s ${t('news.past')}:`,
        s: '%ds',
        m: '1m',
        mm: '%dm',
        h: '1h',
        hh: '%dh',
        d: '1d',
        dd: '%dd',
        M: '1m',
        MM: '%dm',
        y: '1y',
        yy: '%dy',
      },
    });
  }, [t]);

  useEffect(() => {
    const id = setInterval(() => {
      if (cycle) setActiveElemIndex((i) => i + 1);
    }, 3000);
    return () => clearInterval(id);
  }, [cycle]);

  const onNewsImageError = (event: SyntheticEvent<HTMLImageElement>) => {
    const img = event.currentTarget;
    if (img.dataset.fallbackApplied === 'true') return;
    img.dataset.fallbackApplied = 'true';
    img.src = NEWS_PLACEHOLDER_SRC;
  };

  const newsTitle = (newsitem: NewsItem) => {
    const label = newsitem.translations[locale];
    if (newsitem.startDate && newsitem.endDate) {
      if (dayjs(newsitem.startDate).unix() > dayjs().unix()) {
        return { time: dayjs(newsitem.startDate).fromNow(), label };
      }
      if (dayjs(newsitem.endDate).unix() > dayjs().unix()) {
        return { time: `${t('news.live')}:`, label };
      }
      return { time: dayjs(newsitem.endDate).fromNow(), label };
    }
    return { time: dayjs(newsitem.date).fromNow(), label };
  };

  const carouselIndex = cycle ? activeElemIndex % Math.max(filteredNews.length, 1) : (hover ?? 0);

  return (
    <HubPanelWrap title={headertext} className="news">
      <div className="hub-news">
        <div className="hub-news-carousel">
          <div className="hub-news-carousel-viewport">
            {filteredNews.map((newsitem, index) => (
              <img
                key={`${newsitem.id}-img`}
                alt={newsitem.message}
                className={`hub-news-slide-image${index === carouselIndex ? ' is-active' : ''}`}
                src={getNewsImageSrc(newsitem.imageLink)}
                onError={onNewsImageError}
              />
            ))}
          </div>
        </div>

        <ul className="hub-news-list">
          {filteredNews.map((newsitem, index) => {
            const { time, label } = newsTitle(newsitem);
            const isActive = cycle && index === carouselIndex;
            const isHover = hover === index;

            return (
              <li key={`${newsitem.id}-li`} data-news-item={newsitem.id}>
                <a
                  href={newsitem.link}
                  target="_blank"
                  rel="noopener noreferrer"
                  className={`hub-news-item${isActive ? ' is-active' : ''}${isHover ? ' is-hover' : ''}`}
                  onMouseEnter={() => setHover(index)}
                  onFocus={() => setHover(index)}
                >
                  <span className="hub-news-time">{time}</span>
                  <span className="hub-news-label">{label}</span>
                </a>
              </li>
            );
          })}
        </ul>

        <div className="hub-news-footer">
          <HubSwitch
            id="news-cycle-checkbox"
            className="hub-news-autocycle"
            label={t('news.autoprogress')}
            checked={cycle}
            onChange={(isSelected) => dispatch({ type: 'SET_NEWS_AUTO_CYCLE', payload: isSelected })}
          />
        </div>
      </div>
    </HubPanelWrap>
  );
};

export default NewsPanel;
