// src/components/panels/FissuresPanel.vue
<template>
  <HubPanelWrap :title="headertext" class="fissures">
    <b-list-group>
      <b-list-group-item
        :style="styleObject"
        v-for="(fissure, index) in filteredFissures"
        :key="fissure.id"
        class="list-group-item-borderless"
        :class="{ 'pb-0': index !== filteredFissures.length - 1 }"
      >
        <span class="pull-left">
          <HubImg
            :src="determineImg(fissure)"
            :name="fissure.tier"
            class="li-mission-decorator li-mission-decorator-lg"
            height="24px"
            width="24px"
          />
          <b>{{ fissure.node }}</b> | {{ fissure.missionType }} |
          {{ fissure.tier }}
        </span>

        <span class="pull-right">
          <TimeBadge :starttime="fissure.activation" :endtime="fissure.expiry" :interval="1000" style="padding: 5px" />
          <HubImg
            v-if="fissure.isStorm"
            :src="archwing"
            :name="$t('fissures.voidstorm')"
            class="li-mission-decorator li-mission-decorator-lg"
            height="24px"
            width="24px"
          />
        </span>
      </b-list-group-item>

      <NoDataItem v-if="filteredFissures.length === 0" :text="headertext" :overrideBorder="true" />
      <b-list-group-item class="list-group-item-borderbottom">
        <b-form-group :label="$t('fissures.choice')" v-slot="{ ariaDescribedby }">
          <b-form-radio-group
            v-model="check"
            :options="options"
            :aria-describedby="ariaDescribedby"
            button-variant="outline-primary"
            size="sm"
            name="radio-btn-outline"
            buttons
          ></b-form-radio-group>
        </b-form-group>
      </b-list-group-item>
    </b-list-group>
  </HubPanelWrap>
</template>

<script>
import { mapGetters } from 'vuex';
import TimeBadge from '@/components/TimeBadge.vue';
import HubImg from '@/components/HubImg.vue';
import NoDataItem from '@/components/NoDataItem.vue';
import HubPanelWrap from '@/components/HubPanelWrap';
import { cdn } from '@/utilities';

const archwing = cdn('svg/archwing.svg');

const fissureIcons = [];
const lith = cdn('svg/fissures/1.svg');
const meso = cdn('svg/fissures/2.svg');
const neo = cdn('svg/fissures/3.svg');
const axi = cdn('svg/fissures/4.svg');
const requiem = cdn('svg/fissures/5.svg');
fissureIcons.push(lith, meso, neo, axi, requiem);

export default {
  name: 'fissure-panel',
  props: ['fissures'],
  computed: {
    ...mapGetters('worldstate', ['fissureDisplays', 'fissurePlanetStates']),
    headertext() {
      return this.$t('fissures.header');
    },
    check: {
      get() {
        return this.fissureDisplays;
      },
      set(value) {
        this.$store.commit('worldstate/commitFissureDisplaysState', [value]);
      },
    },
    filteredFissures: function () {
      const pState = [];
      Object.keys(this.fissurePlanetStates).forEach((p) => {
        if (this.fissurePlanetStates[p].state) {
          pState.push(p);
        }
      });
      const planets = new RegExp(`(${pState.join('|')})`, 'i');
      return this.fissures
        .filter((fissure) => {
          const isFiltered = planets.test(fissure.node);
          let include = !fissure.expired;
          if (fissure.isStorm) {
            include = include && this.check.includes('storms');
          } else {
            include = include && this.check.includes('fissures');
          }
          return (pState.length > 0 ? !isFiltered : true) && include;
        })
        .sort((a, b) => {
          return a.isStorm && !b.isStorm ? 1 : !a.isStorm && b.isStorm ? -1 : a.tierNum - b.tierNum;
        });
    },
  },
  methods: {
    determineImg: function (fissure) {
      return fissureIcons[fissure.tierNum - 1] || lith;
    },
  },
  data() {
    return {
      styleObject: {
        display: 'inline',
        'vertical-align': 'middle',
      },
      archwing,
      options: [
        { text: this.$t('fissures.header'), value: 'fissures' },
        { text: this.$t('fissures.both'), value: 'fissures-storms' },
        { text: this.$t('fissures.voidstorm'), value: 'storms' },
      ],
    };
  },
  components: {
    TimeBadge,
    HubImg,
    NoDataItem,
    HubPanelWrap,
  },
};
</script>

// components/panels/worldstate/FissuresPanel/FissuresPanel.component.tsx
'use client';
import './FissuresPanel.component.scss';

import { useMemo, type FC } from 'react';
import { Tooltip } from '@heroui/react';
import { useTranslation } from 'react-i18next';
import { cdn } from '@/lib/shared';
import { usePrefs } from '@/lib/providers/PrefsProvider';
import TimeBadge from '@/components/ui/TimeBadge';
import HubImg from '@/components/media/HubImg';
import NoDataItem from '@/components/ui/NoDataItem';
import HubPanelWrap from '@/components/panels/shared/HubPanelWrap';
import { HubPanelList, HubPanelListItem } from '@/components/panels/shared/HubPanelList';
import OmniaFissureIcon, { fissureTierIcon, isOmniaFissure } from './OmniaFissureIcon.component';
import type { FissurePanelKey } from '@/lib/timers/fissurePanelMigration';

const archwing = cdn('svg/archwing.svg');
const steelPath = cdn('svg/sp-logo.svg');

const VARIANT_CLASS: Record<FissurePanelKey, string> = {
  fissures: 'fissures',
  voidStorms: 'void-storms',
  steelPathFissures: 'steel-path-fissures',
};

const VARIANT_TITLE_KEY: Record<FissurePanelKey, string> = {
  fissures: 'fissures.header',
  voidStorms: 'fissures.voidStorms',
  steelPathFissures: 'fissures.steelPathFissures',
};

type Fissure = {
  id: string;
  node: string;
  missionType: string;
  tier: string;
  tierNum: number;
  activation: string;
  expiry: string;
  expired?: boolean;
  isStorm?: boolean;
  isHard?: boolean;
};

type FissuresPanelProps = {
  fissures?: Fissure[];
  variant?: FissurePanelKey;
};

const matchesVariant = (fissure: Fissure, variant: FissurePanelKey): boolean => {
  if (fissure.expired) return false;
  if (variant === 'voidStorms') return Boolean(fissure.isStorm);
  if (variant === 'steelPathFissures') return Boolean(fissure.isHard);
  return !fissure.isStorm && !fissure.isHard;
};

const FissuresPanel: FC<FissuresPanelProps> = ({ fissures = [], variant = 'fissures' }: FissuresPanelProps) => {
  const { t } = useTranslation();
  const { state } = usePrefs();
  const headertext = t(VARIANT_TITLE_KEY[variant]);

  const filteredFissures = useMemo(() => {
    const pState: string[] = [];
    Object.keys(state.fissurePlanets).forEach((p) => {
      if (state.fissurePlanets[p].state) pState.push(p);
    });
    const planets = new RegExp(`(${pState.join('|')})`, 'i');

    return fissures
      .filter((fissure) => {
        const isFiltered = planets.test(fissure.node);
        return (pState.length > 0 ? !isFiltered : true) && matchesVariant(fissure, variant);
      })
      .sort((a, b) => {
        if (a.tierNum < b.tierNum) return -1;
        if (a.tierNum > b.tierNum) return 1;
        return 0;
      });
  }, [fissures, state.fissurePlanets, variant]);

  const titleAddon =
    variant === 'voidStorms' ? (
      <HubImg
        src={archwing}
        name={t('fissures.voidstorm')}
        className="hub-panel-title-icon li-mission-decorator li-mission-decorator-lg"
        height="24px"
        width="24px"
      />
    ) : variant === 'steelPathFissures' ? (
      <HubImg
        src={steelPath}
        name={t('fissures.steelPath')}
        className="hub-panel-title-icon li-mission-decorator li-mission-decorator-lg no-invert"
        height="24px"
        width="24px"
      />
    ) : undefined;

  return (
    <HubPanelWrap title={headertext} titleAddon={titleAddon} className={VARIANT_CLASS[variant]}>
      <HubPanelList>
        {filteredFissures.map((fissure, index) => (
          <HubPanelListItem
            key={fissure.id}
            borderless={index !== filteredFissures.length - 1}
            compact={index !== filteredFissures.length - 1}
          >
            <div className="hub-panel-row">
              <span className="hub-panel-row-main hub-inline-row">
                <Tooltip delay={400}>
                  <Tooltip.Trigger>
                    {isOmniaFissure(fissure) ? (
                      <OmniaFissureIcon
                        label={fissure.tier}
                        className="li-mission-decorator li-mission-decorator-lg hub-fissure-tier-icon"
                      />
                    ) : (
                      <HubImg
                        src={fissureTierIcon(fissure)}
                        name={fissure.tier}
                        showTitle={false}
                        className="li-mission-decorator li-mission-decorator-lg hub-fissure-tier-icon"
                        height="24px"
                        width="24px"
                      />
                    )}
                  </Tooltip.Trigger>
                  <Tooltip.Content>{fissure.tier}</Tooltip.Content>
                </Tooltip>
                <span>
                  <b>{fissure.node}</b> | {fissure.missionType}
                </span>
              </span>
              <span className="hub-panel-row-side">
                <TimeBadge
                  starttime={fissure.activation}
                  endtime={fissure.expiry}
                  interval={1000}
                  pullright={false}
                  style={{ padding: '5px' }}
                />
              </span>
            </div>
          </HubPanelListItem>
        ))}
        {filteredFissures.length === 0 && <NoDataItem text={headertext} overrideBorder />}
      </HubPanelList>
    </HubPanelWrap>
  );
};
export default FissuresPanel;
