// src/components/HubPanelWrap.vue
<template>
  <b-col md="4" data-packer-item="true" class="panel-header binpacker-item mt-2">
    <h4 class="text-center header-panel">{{ title }}</h4>
    <slot></slot>
  </b-col>
</template>

<script>
export default {
  name: 'HubPanelWrap',
  props: ['title'],
  data() {
    return {};
  },
  components: {},
};
</script>

// components/HubPanelWrap.jsx
export default {
  name: 'HubPanelWrap',
  props: {
    title: {
      type: String,
      default: () => '',
    },
  },
  render() {
    return (
      <b-col md={4} data-packer-item="true" class="panel-header binpacker-item mt-2">
        <h4 className="text-center header-panel">{this.title}</h4>
        {this.$slots.default}
      </b-col>
    );
  },
};
