// apps/next/components/media/SynthesisImg/SynthesisImg.component.tsx
'use client';
import './SynthesisImg.component.scss';

import type { FC } from 'react';

import HubImg from '@/components/media/HubImg';
import { useSynthesisPreview } from '@/components/media/SynthesisImg/SynthesisPreview';
import { optimize, cdn } from '@wfcd/shared';

const synthesisSrc = (stub: string) => cdn(`webp/synthesis/${stub}.webp`);

const imgs: Record<string, string> = {
  'Ancient Disruptor': optimize(synthesisSrc('ancient_disruptor')),
  'Ancient Healer': optimize(synthesisSrc('ancient_healer')),
  'Anti MOA [Research]': optimize(synthesisSrc('anti_moa')),
  'Arid Eviscerator [Research]': optimize(synthesisSrc('arid_eviscerator')),
  Ballista: optimize(synthesisSrc('ballista')),
  Boiler: optimize(synthesisSrc('boiler')),
  Bombard: optimize(synthesisSrc('bombard')),
  'Brood Mother': optimize(synthesisSrc('brood_mother')),
  Butcher: optimize(synthesisSrc('butcher')),
  Charger: optimize(synthesisSrc('charger')),
  Commander: optimize(synthesisSrc('commander')),
  'Corrupted Ancient [Research]': optimize(synthesisSrc('corrupted_ancient')),
  'Corrupted Bombard': optimize(synthesisSrc('corrupted_bombard')),
  'Corrupted Butcher': optimize(synthesisSrc('corrupted_butcher')),
  'Corrupted Crewman': optimize(synthesisSrc('corrupted_crewman')),
  'Corrupted Heavy Gunner': optimize(synthesisSrc('corrupted_heavy_gunner')),
  'Corrupted Lancer': optimize(synthesisSrc('corrupted_lancer')),
  'Corrupted Nullifier': optimize(synthesisSrc('corrupted_nullifier')),
  Crawler: optimize(synthesisSrc('crawler')),
  'Crewman [Research]': optimize(synthesisSrc('crewman')),
  'Drahk Master': optimize(synthesisSrc('drahk_master')),
  'Elite Crewman': optimize(synthesisSrc('elite_crewman')),
  Eviscerator: optimize(synthesisSrc('eviscerator')),
  'Fusion MOA': optimize(synthesisSrc('fusion_moa')),
  'Guardsman [Research]': optimize(synthesisSrc('guardsman')),
  'Heavy Gunner': optimize(synthesisSrc('heavy_gunner')),
  Hellion: optimize(synthesisSrc('hellion')),
  'Lancer [Research]': optimize(synthesisSrc('lancer')),
  Leaper: optimize(synthesisSrc('leaper')),
  MOA: optimize(synthesisSrc('moa')),
  Napalm: optimize(synthesisSrc('napalm')),
  'Nullifier Crewman': optimize(synthesisSrc('nullifier_crewman')),
  'Runner [Research]': optimize(synthesisSrc('runner')),
  Scorch: optimize(synthesisSrc('scorch')),
  Scorpion: optimize(synthesisSrc('scorpion')),
  'Seeker / Frontier Seeker': optimize(synthesisSrc('seeker')),
  'Shield Lancer': optimize(synthesisSrc('shield_lancer')),
  'Swarm-Mutalist MOA': optimize(synthesisSrc('swarm-mutalist_moa')),
  Trooper: optimize(synthesisSrc('trooper')),
};

type SynthesisImgProps = {
  name: string;
  image: string;
  size?: number;
  tooltip?: boolean;
};

const SynthesisImg: FC<SynthesisImgProps> = ({ name, image, size = 32, tooltip = true }: SynthesisImgProps) => {
  const preview = useSynthesisPreview();
  const fullSrc = image ? synthesisSrc(image) : null;
  const thumbSrc = fullSrc ? optimize(fullSrc) : imgs[name];

  if (!thumbSrc) return null;

  const openPreview = (target: HTMLElement) => {
    if (!tooltip || !preview || !fullSrc) return;
    preview.open(name, fullSrc, target);
  };

  return (
    <span
      className="hub-async-thumb-trigger synth-portrait-trigger"
      onMouseEnter={(event) => openPreview(event.currentTarget)}
      onMouseLeave={() => preview?.close()}
      onFocus={(event) => openPreview(event.currentTarget)}
      onBlur={() => preview?.close()}
    >
      <HubImg
        src={thumbSrc}
        name={name}
        width={String(size)}
        height={String(size)}
        className="synth-portrait"
        style={{ width: size, height: size }}
        showTitle={false}
      />
    </span>
  );
};

export default SynthesisImg;

// components/SynthesisImg.vue
<template>
  <HubImg :src="src" :name="name" :title="name" :height="height" :width="width" fluid :alt="name" />
</template>

<!--  -->
<script>
import HubImg from '@/components/HubImg';
import { optimize, cdn } from '@/services/utilities';

const translate = (stub) => (stub ? optimize(cdn(`webp/synthesis/${stub}.webp`)) : null);

const imgs = {
  'Ancient Disruptor': optimize(cdn('webp/synthesis/ancient_disruptor.webp')),
  'Ancient Healer': optimize(cdn('webp/synthesis/ancient_healer.webp')),
  'Anti MOA [Research]': optimize(cdn('webp/synthesis/anti_moa.webp')),
  'Arid Eviscerator [Research]': optimize(cdn('webp/synthesis/arid_eviscerator.webp')),
  Ballista: optimize(cdn('webp/synthesis/ballista.webp')),
  Boiler: optimize(cdn('webp/synthesis/boiler.webp')),
  Bombard: optimize(cdn('webp/synthesis/bombard.webp')),
  'Brood Mother': optimize(cdn('webp/synthesis/brood_mother.webp')),
  Butcher: optimize(cdn('webp/synthesis/butcher.webp')),
  Charger: optimize(cdn('webp/synthesis/charger.webp')),
  Commander: optimize(cdn('webp/synthesis/commander.webp')),
  'Corrupted Ancient [Research]': optimize(cdn('webp/synthesis/corrupted_ancient.webp')),
  'Corrupted Bombard': optimize(cdn('webp/synthesis/corrupted_bombard.webp')),
  'Corrupted Butcher': optimize(cdn('webp/synthesis/corrupted_butcher.webp')),
  'Corrupted Crewman': optimize(cdn('webp/synthesis/corrupted_crewman.webp')),
  'Corrupted Heavy Gunner': optimize(cdn('webp/synthesis/corrupted_heavy_gunner.webp')),
  'Corrupted Lancer': optimize(cdn('webp/synthesis/corrupted_lancer.webp')),
  'Corrupted Nullifier': optimize(cdn('webp/synthesis/corrupted_nullifier.webp')),
  Crawler: optimize(cdn('webp/synthesis/crawler.webp')),
  'Crewman [Research]': optimize(cdn('webp/synthesis/crewman.webp')),
  'Drahk Master': optimize(cdn('webp/synthesis/drahk_master.webp')),
  'Elite Crewman': optimize(cdn('webp/synthesis/elite_crewman.webp')),
  Eviscerator: optimize(cdn('webp/synthesis/eviscerator.webp')),
  'Fusion MOA': optimize(cdn('webp/synthesis/fusion_moa.webp')),
  'Guardsman [Research]': optimize(cdn('webp/synthesis/guardsman.webp')),
  'Heavy Gunner': optimize(cdn('webp/synthesis/heavy_gunner.webp')),
  Hellion: optimize(cdn('webp/synthesis/hellion.webp')),
  'Lancer [Research]': optimize(cdn('webp/synthesis/lancer.webp')),
  Leaper: optimize(cdn('webp/synthesis/leaper.webp')),
  MOA: optimize(cdn('webp/synthesis/moa.webp')),
  Napalm: optimize(cdn('webp/synthesis/napalm.webp')),
  'Nullifier Crewman': optimize(cdn('webp/synthesis/nullifier_crewman.webp')),
  'Runner [Research]': optimize(cdn('webp/synthesis/runner.webp')),
  Scorch: optimize(cdn('webp/synthesis/scorch.webp')),
  Scorpion: optimize(cdn('webp/synthesis/scorpion.webp')),
  'Seeker / Frontier Seeker': optimize(cdn('webp/synthesis/seeker.webp')),
  'Shield Lancer': optimize(cdn('webp/synthesis/shield_lancer.webp')),
  'Swarm-Mutalist MOA': optimize(cdn('webp/synthesis/swarm-mutalist_moa.webp')),
  Trooper: optimize(cdn('webp/synthesis/trooper.webp')),
};

export default {
  name: 'SynthesisImg',
  components: {
    HubImg,
  },
  props: {
    name: {
      type: String,
      required: true,
    },
    width: {
      type: String,
      default: 'auto',
    },
    height: {
      type: String,
      default: '100px',
    },
    image: { type: String, required: true },
  },
  data() {
    return {
      target: this.name,
      src: translate(this.image) || imgs[this.name],
    };
  },
};
</script>
