// components/HubImg.vue
<template>
  <span v-b-tooltip.auto :title="name">
    <img :src="src" :name="name" :height="height" :width="width" :alt="name" />
  </span>
</template>

<script>
export default {
  name: 'HubImg',
  props: {
    src: {
      type: String,
      required: true,
    },
    name: {
      type: String,
      default: 'Name',
    },
    width: {
      type: String,
      default: '15px',
    },
    height: {
      type: String,
      default: '15px',
    },
  },
};
</script>

// components/media/HubImg/HubImg.component.tsx
'use client';
import './HubImg.component.scss';

import type { CSSProperties, ReactNode, FC } from 'react';

type HubImgProps = {
  src: string;
  name?: string;
  width?: string;
  height?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
  /** When false, omit native title tooltip (e.g. when wrapped in HeroUI Tooltip). */
  showTitle?: boolean;
};
const HubImg: FC<HubImgProps> = ({
  src,
  name = 'Name',
  width = '15px',
  height = '15px',
  className,
  style,
  showTitle = true,
}: HubImgProps) => {
  const widthPx = Number.parseInt(width, 10);
  const heightPx = Number.parseInt(height, 10);

  return (
    <span title={showTitle ? name : undefined} className={`hub-img ${className ?? ''}`.trim()} style={style}>
      <img
        src={src}
        width={Number.isFinite(widthPx) ? widthPx : undefined}
        height={Number.isFinite(heightPx) ? heightPx : undefined}
        alt={name}
      />
    </span>
  );
};
export default HubImg;
