// components/panels/shared/HubPanelWrap/HubPanelWrap.component.tsx
'use client';
import './HubPanelWrap.component.scss';

import type { ReactNode, FC } from 'react';
import { Card } from '@heroui/react';

type HubPanelWrapProps = {
  title?: string;
  titleAddon?: ReactNode;
  className?: string;
  children: ReactNode;
};

const HubPanelWrap: FC<HubPanelWrapProps> = ({
  title = '',
  titleAddon,
  className,
  children,
}: HubPanelWrapProps) => {
  return (
    <Card data-packer-item='true' className={`hub-panel-surface binpacker-item ${className ?? ''}`}>
      {title ? (
        <Card.Header className='hub-panel-header'>
          <Card.Title className={`hub-panel-title${titleAddon ? ' hub-panel-title-with-addon' : ''}`}>
            <span>{title}</span>
            {titleAddon ? <span className='hub-panel-title-addon'>{titleAddon}</span> : null}
          </Card.Title>
        </Card.Header>
      ) : null}
      <Card.Content className='hub-panel-content'>{children}</Card.Content>
    </Card>
  );
};

export default HubPanelWrap;

// src/components/HubPanelWrap.vue
<template>
  <b-col md="4" data-packer-item="true" class="panel-header binpacker-item mt-2">
    <h4 class="text-center header-panel">{{ title }}</h4>
    <slot></slot>
  </b-col>
</template>

<script>
export default {
  name: 'HubPanelWrap',
  props: ['title'],
  data() {
    return {};
  },
  components: {},
};
</script>
