// components/panels/InvasionsPanel.vue
<template>
  <HubPanelWrap :title="headertext" class="invasions" :class="{ 'no-content': invasions.length === 0 }">
    <b-list-group>
      <b-list-group-item
        :style="styleObject"
        v-for="(invasion, index) in ongoing(invasions).splice(0, maxInvasions)"
        :key="invasion.id"
        v-bind:class="{
          'list-group-item-borderless': index < ongoing(invasions).length - 1,
          'list-group-item-borderbottom': index === ongoing(invasions).length - 1,
        }"
      >
        <Invasion :invasion="invasion"></Invasion>
      </b-list-group-item>
      <b-list-group-item
        class="list-group-item-borderbottom"
        v-if="ongoing(invasions).length > maxInvasions"
        style="padding: 0"
      >
        <Spoiler :init="initialStatus" @toggle="updatePanelStatus()">
          <b-list-group>
            <b-list-group-item
              :style="styleObject"
              v-for="(invasion, index) in ongoing(invasions).splice(maxInvasions)"
              :key="invasion.id"
              v-bind:class="{
                'list-group-item-borderless': index < ongoing(invasions).length - 1,
                'list-group-item-borderbottom': index === ongoing(invasions).length - 1,
              }"
            >
              <Invasion :invasion="invasion"></Invasion>
            </b-list-group-item>
          </b-list-group>
        </Spoiler>
      </b-list-group-item>
      <NoDataItem v-if="invasions.length === 0" :text="headertext" />
    </b-list-group>
  </HubPanelWrap>
</template>

<script>
import NoDataItem from '@/components/NoDataItem.vue';
import HubPanelWrap from '@/components/HubPanelWrap';
import Spoiler from '@/components/Spoiler';
import Invasion from '@/components/Invasion';
import { mapGetters } from 'vuex';

export default {
  name: 'InvasionsPanel',
  props: ['invasions'],
  computed: {
    ...mapGetters('worldstate', ['componentState']),
    headertext() {
      return this.$t('invasions.header');
    },
    maxInvasions() {
      return 5;
    },
    initialStatus() {
      const state = this.componentState.invasions;
      return state.expand;
    },
  },
  data() {
    return {
      styleObject: {
        display: 'inline',
      },
    };
  },
  methods: {
    ongoing: function (invasions) {
      return invasions.filter((invasion) => !invasion.completed);
    },
    updatePanelStatus: function () {
      const state = this.componentState.invasions;
      state.expand = !state.expand;
      this.$store.commit('worldstate/commitComponent', ['invasions', state]);
    },
  },
  components: {
    Invasion,
    Spoiler,
    NoDataItem,
    HubPanelWrap,
  },
};
</script>

// components/panels/InvasionsPanel.jsx
import { mapGetters } from 'vuex';
import NoDataItem from '@/components/NoDataItem.jsx';
import HubPanelWrap from '@/components/HubPanelWrap.jsx';
import Spoiler from '@/components/Spoiler.jsx';
import InvasionItem from '@/components/InvasionItem/InvasionItem.jsx';

const styles = {
  inline: {
    display: 'inline',
  },
  nopad: {
    padding: 0,
  },
  border(index, count) {
    if (index < count - 1) return 'list-group-item-borderless';
    if (index === count - 1) return 'list-group-item-borderbottom';
    return '';
  },
};

export default {
  name: 'InvasionsPanel',
  props: {
    invasions: {
      type: Array,
      default: () => [],
    },
  },
  computed: {
    ...mapGetters('worldstate', ['componentState']),
    headertext() {
      return this.$t('invasions.header');
    },
    maxInvasions() {
      return 1;
    },
    initialStatus() {
      return this.componentState?.invasions?.expand;
    },
    current() {
      return this.ongoing.slice(0, this.maxInvasions);
    },
    ongoing() {
      return this.invasions.filter((invasion) => !invasion.completed);
    },
    spoiler() {
      return this.ongoing.slice(this.maxInvasions, this.ongoing.length);
    },
  },
  methods: {
    updatePanelStatus() {
      const newState = {
        ...this.componentState.invasions,
        expand: !this.componentState.invasions.expand,
      };
      this.$store.commit('worldstate/commitComponent', ['invasions', newState]);
    },
  },
  render() {
    try {
      return (
        <HubPanelWrap title={this.headertext} class={`invasions ${!this.invasions.length && 'no-content'}`}>
          <b-list-group>
            {this.current.map((invasion, index) => {
              return (
                <b-list-group-item
                  key={invasion.id}
                  style={styles.inline}
                  class={styles.border(index, this.ongoing.length)}
                >
                  <InvasionItem invasion={invasion} />
                </b-list-group-item>
              );
            })}
            {this.ongoing.length > this.maxInvasions && (
              <b-list-group-item className="list-group-item-borderbottom" style={styles.nopad}>
                <Spoiler init={this.initialStatus} onToggle={this.updatePanelStatus}>
                  <b-list-group>
                    {this.spoiler.map((invasion, index) => {
                      return (
                        <b-list-group-item
                          key={invasion.id}
                          style={styles.inline}
                          class={styles.border(index, this.ongoing.length)}
                        >
                          <InvasionItem invasion={invasion} />
                        </b-list-group-item>
                      );
                    })}
                  </b-list-group>
                </Spoiler>
              </b-list-group-item>
            )}
            {this.current.length === 0 && <NoDataItem text={this.headertext} />}
          </b-list-group>
        </HubPanelWrap>
      );
    } catch (e) {
      console.error('Failed to load InvasionPanel', e);
      return <span />;
    }
  },
};
