// components/panels/worldstate/SortiePanel/SortiePanel.component.tsx
'use client';
import './SortiePanel.component.scss';
import type { FC } from 'react';

import dayjs from 'dayjs';
import { useTranslation } from 'react-i18next';
import { cdn } from '@/lib/shared';
import HubImg from '@/components/media/HubImg';
import TimeBadge from '@/components/ui/TimeBadge';
import HubPanelWrap from '@/components/panels/shared/HubPanelWrap';
import { HubPanelList, HubPanelListItem } from '@/components/panels/shared/HubPanelList';

const corpus = cdn('svg/factions/corpus.svg');
const corrupted = cdn('svg/factions/corrupted.svg');
const grineer = cdn('svg/factions/grineer.svg');
const infested = cdn('svg/factions/infested.svg');
const sentient = cdn('svg/factions/sentient.svg');
const narmer = cdn('svg/factions/narmer2.svg');

const fImg: Record<string, string> = {
  corpus,
  grineer,
  infested,
  infestation: infested,
  corrupted,
  orokin: corrupted,
  sentient,
  narmer,
};

type SortieMission = {
  missionType?: string;
  type?: string;
  node: string;
  modifier: string;
  modifierDescription?: string;
};

type Sortie = {
  faction?: string;
  boss?: string;
  expiry?: string;
  missions?: SortieMission[];
  variants?: SortieMission[];
};

type SortiePanelProps = {
  sortie?: Sortie;
};

const SortiePanel: FC<SortiePanelProps> = ({ sortie = {} }: SortiePanelProps) => {
  const { t } = useTranslation();
  const missions = (sortie.variants?.length ? sortie.variants : sortie.missions) || [];
  const headertext = sortie.missions?.length ? t('sortie.hunt.header') : t('sortie.header');
  const factionImg = fImg[sortie.faction?.toLowerCase() ?? ''] || corrupted;
  const now = dayjs().toISOString();

  return (
    <HubPanelWrap title={headertext} className="sortie">
      <HubPanelList>
        <HubPanelListItem borderless compact>
          <div className="hub-panel-row">
            <span className="hub-panel-row-main">
              <h4 className="my-0 hub-inline-title">
                <HubImg
                  src={factionImg}
                  name={sortie.faction ?? ''}
                  className="li-mission-decorator li-mission-decorator-lg invert hub-inline-title-icon"
                  width="25px"
                  height="25px"
                />
                {sortie.boss}
              </h4>
            </span>
            <span className="hub-panel-row-side">
              <TimeBadge starttime={now} endtime={sortie.expiry} interval={1000} pullright={false} />
            </span>
          </div>
        </HubPanelListItem>
        {missions.map((mission, index) => (
          <HubPanelListItem
            key={`sortie-${index}`}
            borderless={index !== missions.length - 1}
            borderBottom={index === missions.length - 1}
            compact={index !== missions.length - 1}
          >
            <div className="hub-sortie-mission ml-3">
              <div className="hub-panel-row hub-panel-row-subtle">
                <span className="hub-panel-row-main">
                  <b>
                    {mission.missionType || mission.type} - {mission.node}
                  </b>
                </span>
                <span className="hub-panel-row-side" title={mission.modifierDescription}>
                  {mission.modifier}
                </span>
              </div>
            </div>
          </HubPanelListItem>
        ))}
      </HubPanelList>
    </HubPanelWrap>
  );
};

export default SortiePanel;

// components/panels/SortiePanel.vue
<template>
  <HubPanelWrap :title="headertext" class="sortie">
    <b-list-group>
      <b-list-group-item :style="styleObject" class="list-group-item-borderless pb-0">
        <span class="pull-left">
          <h4 class="my-0">
            <HubImg :src="factionImg" :name="sortie.faction" :style="missionType" width="20px" height="20px" />
            {{ sortie.boss }}
          </h4>
        </span>
        <TimeBadge :starttime="now" :endtime="sortie.expiry" :interval="1000" />
      </b-list-group-item>
      <b-list-group-item
        v-for="(mission, index) in sortie.variants"
        :key="`sortie-${index}`"
        :style="styleObject"
        :class="{
          'list-group-item-borderless': index !== sortie.variants.length - 1,
          'pb-0': index !== sortie.variants.length - 1,
          'list-group-item-borderbottom': index === sortie.variants.length - 1,
        }"
      >
        <div class="ml-3">
          <span class="pull-left pr-2">
            <b>{{ mission.missionType }} - {{ mission.node }}</b>
          </span>
          <span v-b-tooltip.top :title="mission.modifierDescription" class="pull-left">
            {{ mission.modifier }}
          </span>
        </div>
      </b-list-group-item>
    </b-list-group>
  </HubPanelWrap>
</template>

<script>
import dayjs from 'dayjs';

import HubImg from '@/components/HubImg.vue';
import TimeBadge from '@/components/TimeBadge.vue';
import HubPanelWrap from '@/components/HubPanelWrap';
import { cdn } from '@/services/utilities';

const corpus = cdn('svg/factions/corpus.svg');
const corrupted = cdn('svg/factions/corrupted.svg');
const grineer = cdn('svg/factions/grineer.svg');
const infested = cdn('svg/factions/infested.svg');
const sentient = cdn('svg/factions/sentient.svg');

export default {
  name: 'SortiePanel',
  components: {
    TimeBadge,
    HubImg,
    HubPanelWrap,
  },
  props: ['sortie'],
  data() {
    return {
      styleObject: {
        display: 'inline',
      },
      missionType: {
        filter: 'invert(100%)',
        'margin-top': '-3px',
        'margin-right': '5px',
        width: '25px',
        height: '25px',
      },
    };
  },
  computed: {
    now() {
      return dayjs().toISOString();
    },
    headertext() {
      return this.$t('sortie.header');
    },
    factionImg() {
      const fImg = {
        corpus,
        grineer,
        infested,
        infestation: infested,
        corrupted,
        orokin: corrupted,
        sentient,
      };
      return fImg[this.$props.sortie.faction.toLowerCase()] || corrupted;
    },
  },
};
</script>
