// components/panels/NightwavePanel.vue
<template>
  <HubPanelWrap :title="headertext" class="nightwave">
    <b-list-group v-if="nightwave && nightwave.activeChallenges">
      <b-list-group-item
        v-for="(challenge, index) in nightwave.activeChallenges"
        :key="challenge.id"
        :style="styleObject"
        :class="{
          'list-group-item-borderless': index !== nightwave.activeChallenges.length - 1,
          'pb-0': index !== nightwave.activeChallenges.length - 1,
          'list-group-item-borderbottom': index === nightwave.activeChallenges.length - 1,
        }"
      >
        <span class="pull-left">
          <HubImg
            :src="challenge.isDaily ? daily : challenge.isElite ? elite : weekly"
            :name="type(challenge)"
            class="li-mission-decorator li-mission-decorator-lg invert"
            :height="challenge.isDaily ? '15px' : '24px'"
            width="24px"
          />
        </span>
        <span v-b-tooltip.right :title="challenge.desc" class="pull-left">
          {{ challenge.title }}
        </span>

        <TimeBadge class="pull-right" :starttime="challenge.activation" :endtime="challenge.expiry" :interval="1000" />
        <b-badge :variant="challenge.isDaily ? 'success' : challenge.isElite ? 'danger' : 'warning'" class="pull-right">
          <HubImg :src="standing" name="Standing Gain" class="invert" height="12px" width="12px" />
          {{ challenge.reputation }}
        </b-badge>
      </b-list-group-item>
    </b-list-group>
    <b-list-group v-if="!nightwave || nightwave.activeChallenges.length === 0">
      <NoDataItem :text="headertext" />
    </b-list-group>
  </HubPanelWrap>
</template>

<script>
import TimeBadge from '@/components/TimeBadge.vue';
import NoDataItem from '@/components/NoDataItem.vue';
import HubPanelWrap from '@/components/HubPanelWrap';
import HubImg from '@/components/HubImg';
import { cdn } from '@/services/utilities';

const daily = cdn('webp/nightwave/daily.webp');
const weekly = cdn('webp/nightwave/weekly.webp');
const elite = cdn('webp/nightwave/elite.webp');
const standing = cdn('svg/standing.svg');

export default {
  name: 'NightwavePanel',
  components: {
    TimeBadge,
    NoDataItem,
    HubPanelWrap,
    HubImg,
  },
  props: ['nightwave'],
  data() {
    return {
      styleObject: {
        display: 'inline',
      },
      daily,
      weekly,
      elite,
      standing,
    };
  },
  computed: {
    headertext() {
      return this.$t('nightwave.header');
    },
  },
  methods: {
    type(challenge) {
      return this.$t(`nightwave.${challenge.isDaily ? 'daily' : challenge.isElite ? 'elite' : 'weekly'}`);
    },
  },
};
</script>

// components/panels/worldstate/NightwavePanel/NightwavePanel.component.tsx
'use client';
import './NightwavePanel.component.scss';
import type { FC } from 'react';

import { Chip } from '@heroui/react';
import { useTranslation } from 'react-i18next';
import { cdn } from '@/lib/shared';
import TimeBadge from '@/components/ui/TimeBadge';
import NoDataItem from '@/components/ui/NoDataItem';
import HubPanelWrap from '@/components/panels/shared/HubPanelWrap';
import HubImg from '@/components/media/HubImg';
import { HubPanelList, HubPanelListItem } from '@/components/panels/shared/HubPanelList';

const daily = cdn('webp/nightwave/daily.webp');
const weekly = cdn('webp/nightwave/weekly.webp');
const elite = cdn('webp/nightwave/elite.webp');
const standing = cdn('svg/standing.svg');

type NightwaveChallenge = {
  id: string;
  title: string;
  desc: string;
  activation: string;
  expiry: string;
  isDaily?: boolean;
  isElite?: boolean;
  reputation: number;
};

type Nightwave = {
  activeChallenges?: NightwaveChallenge[];
};

type NightwavePanelProps = {
  nightwave?: Nightwave;
};

const NightwavePanel: FC<NightwavePanelProps> = ({ nightwave }: NightwavePanelProps) => {
  const { t } = useTranslation();
  const headertext = t('nightwave.header');
  const challenges = nightwave?.activeChallenges ?? [];

  const type = (challenge: NightwaveChallenge) =>
    t(`nightwave.${challenge.isDaily ? 'daily' : challenge.isElite ? 'elite' : 'weekly'}`);

  return (
    <HubPanelWrap title={headertext} className="nightwave">
      {challenges.length > 0 ? (
        <HubPanelList>
          {challenges.map((challenge, index) => (
            <HubPanelListItem
              key={challenge.id}
              borderless={index !== challenges.length - 1}
              borderBottom={index === challenges.length - 1}
              compact={index !== challenges.length - 1}
            >
              <div className="hub-panel-row">
                <span className="hub-panel-row-main" title={challenge.desc}>
                  <HubImg
                    src={challenge.isDaily ? daily : challenge.isElite ? elite : weekly}
                    name={type(challenge)}
                    className="li-mission-decorator li-mission-decorator-lg invert"
                    height={challenge.isDaily ? '15px' : '24px'}
                    width={challenge.isDaily ? '15px' : '24px'}
                  />
                  {challenge.title}
                </span>
                <span className="hub-panel-row-side">
                  <TimeBadge
                    starttime={challenge.activation}
                    endtime={challenge.expiry}
                    interval={1000}
                    pullright={false}
                  />
                  <Chip
                    color={challenge.isDaily ? 'success' : challenge.isElite ? 'danger' : 'warning'}
                    size="sm"
                    variant="soft"
                    className="hub-standing-chip"
                  >
                    <HubImg src={standing} name="Standing Gain" className="invert" height="12px" width="12px" />
                    {challenge.reputation}
                  </Chip>
                </span>
              </div>
            </HubPanelListItem>
          ))}
        </HubPanelList>
      ) : (
        <NoDataItem text={headertext} />
      )}
    </HubPanelWrap>
  );
};

export default NightwavePanel;
