// src/components/NoDataItem.vue
<template>
  <b-list-group-item class="py-1" :class="{ 'list-group-item-borderbottom': !this.overrideBorder }">
    <span class="dim">
      <HubImg
        :src="loading"
        :name="$t('nav.nodata')"
        width="40px"
        height="40px"
        style="filter: invert(80%); padding-right: 10px"
      />
      <div class="no-content-warning align-middle" style="margin-bottom: 2px">
        {{ $t('nav.nodatatxt', { text: text }) }}
      </div>
    </span>
  </b-list-group-item>
</template>

<script>
import HubImg from '@/components/HubImg.vue';
import { cdn } from '@/utilities';

const loading = cdn('svg/loading.svg');
export default {
  name: 'NoDataItem',
  props: ['text', 'overrideBorder'],
  data() {
    return {
      loading: loading,
    };
  },
  components: {
    HubImg,
  },
};
</script>

// components/ui/NoDataItem/NoDataItem.component.tsx
'use client';
import './NoDataItem.component.scss';
import type { FC } from 'react';

import { useTranslation } from 'react-i18next';
import { cdn } from '@/lib/shared';
import HubImg from '@/components/media/HubImg';

const loading = cdn('svg/loading.svg');

type NoDataItemProps = {
  text?: string;
  overrideBorder?: boolean;
};

const NoDataItem: FC<NoDataItemProps> = ({ text = 'Data', overrideBorder = false }: NoDataItemProps) => {
  const { t } = useTranslation();

  return (
    <div
      className={[
        'hub-no-data-item',
        overrideBorder ? '' : 'hub-no-data-item--border-bottom',
      ]
        .filter(Boolean)
        .join(' ')}
    >
      <span className="dim hub-empty-state">
        <HubImg
          src={loading}
          name={t('nav.nodata')}
          width="40px"
          height="40px"
          className="hub-empty-state-icon"
          style={{ filter: 'invert(80%)' }}
        />

        <div className="no-content-warning align-middle" style={{ marginBottom: '2px' }}>
          {t('nav.nodatatxt', { text })}
        </div>
      </span>
    </div>
  );
};

export default NoDataItem;
